# Generated by Django 3.2.9 on 2022-03-18 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Vm_Info',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vm_name', models.CharField(max_length=80)),
                ('job', models.IntegerField()),
                ('vm_memory', models.IntegerField()),
                ('vm_cpus', models.IntegerField()),
                ('vm_cpu_cores', models.IntegerField()),
                ('vm_disk_size', models.IntegerField()),
                ('template', models.CharField(max_length=80)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='komodoapp.user')),
            ],
        ),
    ]
