# Generated by Django 3.2.9 on 2022-03-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('komodoapp', '0002_rename_user_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vm_info',
            name='vm_cpu_cores',
        ),
    ]
